import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

/**
 * ESLint flat config.
 *
 * `next lint` was removed in Next.js 16, so linting runs through the ESLint CLI
 * (`npm run lint` → `eslint .`). core-web-vitals promotes the rules that affect
 * Core Web Vitals from warnings to errors; the TypeScript config adds
 * typescript-eslint's recommended rules.
 */
export default defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    // Defaults carried over from eslint-config-next.
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the build, not authored here.
    "public/**",
    "docs/**",
  ]),
]);
